# Generated by Django 2.0.3 on 2018-03-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stratup', models.TextField(blank=True, null=True)),
                ('applied_startup', models.TextField(blank=True, null=True)),
                ('mobile', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_up_name', models.CharField(max_length=256)),
                ('start_up_description', models.TextField(blank=True, null=True)),
                ('start_up_members', models.TextField(blank=True, null=True)),
                ('start_up_skills_req', models.TextField(blank=True, null=True)),
                ('start_up_sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventures_name', models.TextField(blank=True, null=True)),
                ('ventures_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventures_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventures_request_start_up_name', models.TextField(blank=True, null=True)),
                ('ventures_request_USP', models.TextField(blank=True, null=True)),
                ('ventures_request_Amount', models.IntegerField()),
            ],
        ),
    ]
